enum DISPLAY_GIFTCARD_ACTION {
  BASE = 'D_GIFTCARD__',
  ADD_CARD = 'D_GIFTCARD__ADD_CARD',
  NEXT_STEP = 'D_GIFTCARD__NEXT_STEP',
  LOADING = 'D_GIFTCARD__LOADING',
  ERROR = 'D_GIFTCARD__ERROR'
}

enum PAYMENT_GIFTCARD_ACTION {
  BASE = 'P_GIFTCARD__',
  ADD_CARD = 'P_GIFTCARD__ADD_CARD'
}

export { DISPLAY_GIFTCARD_ACTION, PAYMENT_GIFTCARD_ACTION };
